CoolBooks/Models/Author.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoolBooks.Models
{
    public class Author
    {
        [Required]
        public int Id { get; set; }

        [Required][MaxLength(20)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(20)]
        public string LastName { get; set; }

        [Required] 
        public DateTime BirthDate { get; set; }
        
        [Required]
        public bool IsDeleted { get; set; }

        [Required]
        public DateTime Created { get; set; }

        [Required]
        public string? CreatedBy { get; set; }

        [ForeignKey("CreatedBy")]
        public virtual CoolBooksUser CoolBooksUser { get; set; }

        public string? UpdatedBy { get; set; }

        public DateTime? LastUpdated { get; set; }

        //[Required]
        public List<Book>? Books { get; set; } = new List<Book>();

        public string ImagePath { get; set; }

        [Required]
        [Range(0.00, 5.00)]
        public double Rating { get; set; }

        // UserID?
        // CreatedBy?
        // Updated?
        // UPdatedBy?

        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }
        public string? Description { get; set; }
        [MaxLength(50)]
        public string? Wiki { get; set; }
    }
}

CoolBooks/Controllers/AuthorsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoolBooks.Data;
using CoolBooks.Models;
using CoolBooks.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace CoolBooks.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly CoolBooksContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly UserManager<CoolBooksUser> userManager;
        private readonly SignInManager<CoolBooksUser> signInManager;

        public AuthorsController(CoolBooksContext context, IWebHostEnvironment hostEnvironment, UserManager<CoolBooksUser> userManager, SignInManager<CoolBooksUser> signInManager)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        // GET: Authors
        public async Task<IActionResult> Index(string searchString, string sortOrder, string currentFilter, int? pageNumber)
        {
            ViewBag.CurrentSort = sortOrder;

            ViewBag.searchString = searchString;

            ViewBag.FirstNameAscDescSortParam = sortOrder == "FirstName ASC" ? "FirstName DESC" : "FirstName ASC";
            ViewBag.LastNameAscDescSortParam = sortOrder == "LastName ASC" ? "LastName DESC" : "LastName ASC";
            ViewBag.BirthDateAscDescSortParam = sortOrder == "BirthDate ASC" ? "BirthDate DESC" : "BirthDate ASC";
            ViewBag.CreatedAscDescSortParam = sortOrder == "Created ASC" ? "Created DESC" : "Created ASC";
            ViewBag.RatingAscDescSortParam = sortOrder == "Rating ASC" ? "Rating DESC" : "Rating ASC";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {

                searchString = currentFilter;
            }

            var authors = _context.Author
                                     //.Include(g => g.Genres)
                                     //.Include(a => a.Authors)
                                     .Where(a => a.IsDeleted != true)
                                     .Select(a => a);
            switch (sortOrder)
            {
                case "FirstName DESC":
                    authors = authors.OrderByDescending(b => b.FirstName);
                    break;
                case "FirstName ASC":
                    authors = authors.OrderBy(b => b.FirstName);
                    break;
                case "LastName DESC":
                    authors = authors.OrderByDescending(b => b.LastName);
                    break;
                case "LastName ASC":
                    authors = authors.OrderBy(b => b.LastName);
                    break;
                case "BirthDate DESC":
                    authors = authors.OrderByDescending(b => b.BirthDate);
                    break;
                case "BirthDate ASC":
                    authors = authors.OrderBy(b => b.BirthDate);
                    break;
                case "Created DESC":
                    authors = authors.OrderByDescending(b => b.Created);
                    break;
                case "Created ASC":
                    authors = authors.OrderBy(b => b.Created);
                    break;
                case "Rating DESC":
                    authors = authors.OrderByDescending(b => b.Rating);
                    break;
                case "Rating ASC":
                    authors = authors.OrderBy(b => b.Rating);
                    break;
                default:
                    authors = authors.OrderBy(b => b.Id);
                    break;
            }
            int pageSize = 10;
            //return View(await authors.ToList());
            return View(await PaginatedList<Author>.CreateAsync(authors.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id, string sortOrder, int? pageNumber)
        {
            AuthorDetailsViewModel vm = new AuthorDetailsViewModel();
            vm.Author = await _context.Author
                                      .FirstOrDefaultAsync(m => m.Id == id);

            ViewBag.TitleAscDescSortParam = sortOrder == "Title ASC" ? "Title DESC" : "Title ASC";
            ViewBag.DescriptionAscDescSortParam = sortOrder == "Description ASC" ? "Description DESC" : "Description ASC";
            ViewBag.GenreAscDescSortParam = sortOrder == "Genre ASC" ? "Genre DESC" : "Genre ASC";
            ViewBag.RatingAscDescSortParam = sortOrder == "Rating ASC" ? "Rating DESC" : "Rating ASC";
            ViewBag.AuthorAscDescSortParam = sortOrder == "Authors ASC" ? "Authors DESC" : "Authors ASC";

            var books = _context.Book.Include(g => g.Genres)
                                     .Include(a => a.Authors)
                                     .Where(b => b.IsDeleted != true)
                                     .Where(b => b.Authors.Any(g => g.Id == id))
                                     .Select(b => b);
            pageNumber = 1;
            switch (sortOrder)
            {
                case "Title DESC":
                    books = books.OrderByDescending(b => b.Title);
                    break;
                case "Title ASC":
                    books = books.OrderBy(b => b.Title);
                    break;
                case "Description DESC":
                    books = books.OrderByDescending(b => b.Description);
                    break;
                case "Description ASC":
                    books = books.OrderBy(b => b.Description);
                    break;
                case "Genre DESC":
                    books = books.OrderByDescending(b => b.Genres);
                    break;
                case "Genre ASC":
                    books = books.OrderBy(b => b.Genres);
                    break;
                case "Rating DESC":
                    books = books.OrderByDescending(b => b.Rating);
                    break;
                case "Rating ASC":
                    books = books.OrderBy(b => b.Rating);
                    break;
                case "Authors DESC":
                    books = books.Include(a => a.Authors
                                                .OrderByDescending(b => b.FirstName));
                    break;
                case "Authors ASC":
                    books = books.Include(a => a.Authors
                                                .OrderBy(b => b.FirstName));
                    break;
                default:
                    books = books.OrderBy(b => b.Id);
                    break;
            }

            int pageSize = 5;
            vm.Books = await PaginatedList<Book>.CreateAsync(books.AsNoTracking(), pageNumber ?? 1, pageSize);
            return View(vm);
        }

        // GET: Authors/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAuthorViewModel authorInput)
        {
            if (ModelState.IsValid)
            {
                Author authorToCreate = new Author();
                var user = await userManager.GetUserAsync(User);

                authorToCreate.FirstName = authorInput.FirstName;
                authorToCreate.LastName = authorInput.LastName;
                authorToCreate.BirthDate = authorInput.BirthDate;
                authorToCreate.CreatedBy = user.Id;
                authorToCreate.Created = DateTime.Now;
                authorToCreate.ImagePath = "";
                authorToCreate.Description = authorInput.Description;
                authorToCreate.Wiki = authorInput.Wiki;

                _context.Add(authorToCreate);
                await _context.SaveChangesAsync();


                //save image
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(authorInput.ImageFile.FileName);
                string extension = Path.GetExtension(authorInput.ImageFile.FileName);

                fileName = authorToCreate.Id + extension; //name it after the books Id

                string path = Path.Combine(wwwRootPath + "/Images/Authors/", fileName);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await authorInput.ImageFile.CopyToAsync(fileStream);
                }

                //update imagepath (kanske inte nödvändig.. men for now!)
                authorToCreate.ImagePath = Path.Combine("/Images/Authors/", fileName);
                _context.Author.Attach(authorToCreate);
                _context.Entry(authorToCreate).State = EntityState.Modified;
                _context.SaveChanges();


                return RedirectToAction(nameof(Index));
            }
            return View(authorInput);
        }

        // GET: Authors/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            EditAuthorViewModel vm = new EditAuthorViewModel();
            var author = await _context.Author.FindAsync(id);

            vm.FirstName = author.FirstName;
            vm.LastName = author.LastName;
            vm.BirthDate = author.BirthDate;

CoolBooks/Views/Authors/Create.cshtml
@model CreateAuthorViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Lägg till författare:</h1>

<h4>Author</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wiki" class="control-label"></label>
                <input asp-for="Wiki" class="form-control" />
                <span asp-validation-for="Wiki" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" accept="image/*" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoolBooks/Views/Authors/Delete.cshtml
@model CoolBooks.Models.Author

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Author</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoolBooks/Views/Authors/Details.cshtml
@model AuthorDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Author.FullName)</h1>


    <hr />    
        <div class="mb-3" style="max-width: 100%;">
           <div style="background: #FFF1F2;" class="row no-gutters">
                <div class="col-md-4">
                   <img src="@Html.DisplayFor(model => model.Author.ImagePath)" class="card-img" alt="...">
                 </div>
                    <div class="col-md-8">
                        <div class="card-body border border-3 border-white rounded">
                            <dl class="row">
                                <dt class = "col-sm-2">
                                    @Html.DisplayNameFor(model => model.Author.FirstName)
                                </dt>
                                <dd class = "col-sm-10">
                                    @Html.DisplayFor(model => model.Author.FirstName)
                                </dd>
                                <dt class = "col-sm-2">
                                    @Html.DisplayNameFor(model => model.Author.LastName)
                                </dt>
                                <dd class = "col-sm-10">
                                    @Html.DisplayFor(model => model.Author.LastName)
                                </dd>
                                <dt class = "col-sm-2">
                                    @Html.DisplayNameFor(model => model.Author.BirthDate)
                                </dt>
                                <dd class = "col-sm-10">
                                    @String.Format("{0:yyyy/MM/dd}", Model.Author.BirthDate)            
                                </dd>
                                <dt class = "col-sm-2">
                                    @Html.DisplayNameFor(model => model.Author.Rating)
                                </dt>
                                <dd class = "col-sm-10">
                                    <partial name="_RatingStars" model="@Model.Author.Rating" />
                                    
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Author.Description)
                                </dt>
                                <dd class ="col-sm-10">
                                    @Model.Author.Description
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Author.Wiki)
                                </dt>
                                <dd class ="col-sm-10">
                                    @if (Model.Author.Wiki != null && @Model.Author.Wiki != "")
                                    {
                                        <a class="link-secondary" href="@Model.Author.Wiki" target="_blank">Wiki</a>
                                    }
                                    else
                                    {
                                        <p><b>Wiki länk saknas! Kontakta Admin@coolbooks.com</b></p>
                                    }
                                    @* target=_blank gör så att vi öppnar ny flik då vi inte vill att användaren försvinner från coolbooks!*@
                                </dd>
                            </dl>
                        </div>
                    </div>
                </div>
              </div>
                           

<div>
        @if (User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Author.Id">Edit |</a>
    }
    <a asp-action="Index">Back to List</a>
</div>


@if (Model.Books.Any())
{

    <partial name="_BooksTable" model="@Model.Books"/>
}
else
{
<h3>Den här författaren har inga böcker tillagda ännu...?</h3>   

}

CoolBooks/Views/Authors/Edit.cshtml
@model EditAuthorViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Author</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wiki" class="control-label"></label>
                <input asp-for="Wiki" class="form-control" />
                <span asp-validation-for="Wiki" class="text-danger"></span>
            </div>

            <p>IsDeleted:</p>
            <div class="form-group form-check">
                
                <label class="form-check-label">                    
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>

            <img src="@Model.ImagePath" class="card-img-thumbnail" alt="..." width="150px" height="223px">
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" accept="image/*" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div> 


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>



        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoolBooks/Views/Authors/Index.cshtml
@*@model IEnumerable<CoolBooks.Models.Author>*@
@model PaginatedList<CoolBooks.Models.Author>
@{
    ViewData["Title"] = "Index";
    var controller = this.ViewContext.RouteData.Values["controller"].ToString();
    var action = this.ViewContext.RouteData.Values["action"].ToString();
    var route = ViewContext.RouteData.Values["id"];
}

<h1>Författare.</h1>

<p>Sortera på:
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.FirstNameAscDescSortParam">Förnamn</a>

    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.LastNameAscDescSortParam">Efternamn</a>

    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.BirthDateAscDescSortParam">Födelsedag</a>

    @*<a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.CreatedAscDescSortParam">Created ASC/DESC</a>*@

    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.RatingAscDescSortParam">Betyg</a>
</p>




<div class="d-flex flex-wrap justify-content-evenly">
    @foreach (var item in Model) {


         <div class="d-flex">
            <div class="m-3 d-flex flex-column justify-content-center align-content-center">
                <a asp-controller="Authors" asp-action="Details" asp-route-id="@item.Id">                
                    <img src=" @Html.DisplayFor(modelItem => item.ImagePath)" class="card-img-thumbnail" alt="..." width="150px" height="225px">
                </a>   
                @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <a asp-controller="Authors" asp-action="Edit" asp-route-id="@item.Id">Edit</a>                
                    <a asp-controller="Authors" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
            </div>
            <div class="d-flex flex-column m-3 border border-3 border-white p-3 rounded" style="width: 320px;">
                <div class="d-flex">
                    <h2>
                        <a class="link-secondary" asp-controller="Authors" asp-action="Details" asp-route-id="@item.Id">                                    
                            @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
                        </a>
                    </h2>
                </div>


                <div>
                    <partial name="_RatingStars" model="@item.Rating" />
                </div>

                <div class="d-flex mb-0">
                    <p class="me-2 mb-0">
                        @String.Format("{0:yyyy/MM/dd}", item.BirthDate)
                    </p>
                
                </div>
                <div class="d-flex">
                    @{
                        string d = item.Description;
                        if (d.Length > 50 && d != null)
                        {
                            d = d.Substring(0, 50);
                            d = d + "...";
                            @d 
                        }
                        else
                        {
                            @d  
                        }
                    }
                    
               
                </div>
                <div class ="d-flex">
                    <a class="link-secondary" asp-controller="Authors" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </div>
                <div class="d-flex">
                    @if (@item.Wiki != null && @item.Wiki != "")
                    {
                        <a class="link-secondary" href="@item.Wiki" target="_blank">Wiki</a>
                    }
                    else
                    {
                        <p><b>Wiki länk saknas! Kontakta Admin@coolbooks.com</b></p>
                    }
                    @* target=_blank gör så att vi öppnar ny flik då vi inte vill att användaren försvinner från coolbooks!*@
                </div>

            </div>        
        </div>
    }
</div>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
@for(int i = 1; i <= Model.TotalPages; i++){
    bool hej = true;
    if (Model.PageIndex == i)
    {
        hej = false;
        
    } 
    else
    {
        hej = true;
        
    }
    var currentDisabled = !hej ? "disabled" : "";
    <a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(i)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @currentDisabled">
    @i
</a>
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>