CoolBooks/Models/Genre.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoolBooks.Models
{
    public class Genre
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public bool IsDeleted { get; set; }

        [Required]
        public DateTime Created { get; set; }

        [Required]
        public string CreatedBy { get; set; }

        [ForeignKey("CreatedBy")]
        public virtual CoolBooksUser CoolBooksUser { get; set; }

        public string? UpdatedBy { get; set; }

        public DateTime? LastUpdated { get; set; }

        //[Required]
        public List<Book> Books { get; set; } = new List<Book>();

        // CreatedBy?
        // Updated?
        // UPdatedBy?
    }
}

CoolBooks/Controllers/GenresController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoolBooks.Data;
using CoolBooks.Models;
using CoolBooks.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace CoolBooks.Controllers
{
    
    public class GenresController : Controller
    {
        private readonly CoolBooksContext _context;
        private readonly UserManager<CoolBooksUser> userManager;
        private readonly SignInManager<CoolBooksUser> signInManager;
        public GenresController(CoolBooksContext context, UserManager<CoolBooksUser> userManager, SignInManager<CoolBooksUser> signInManager)
        {
            _context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        // GET: Genres
        public async Task<IActionResult> Index(string searchString, string sortOrder, string currentFilter, int? pageNumber)
        {
            ViewBag.CurrentSort = sortOrder;

            ViewBag.searchString = searchString;

            ViewBag.FirstNameAscDescSortParam = sortOrder == "Name ASC" ? "Name DESC" : "Name ASC";
            ViewBag.DescriptionAscDescSortParam = sortOrder == "Description ASC" ? "Description DESC" : "Description ASC";    
            ViewBag.CreatedAscDescSortParam = sortOrder == "Created ASC" ? "Created DESC" : "Created ASC";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {

                searchString = currentFilter;
            }

            var genres = _context.Genre
                                     //.Include(g => g.Genres)
                                     //.Include(a => a.Authors)
                                     .Where(b => b.IsDeleted != true)
                                     .Select(b => b);
            switch (sortOrder)
            {
                case "Name DESC":
                    genres = genres.OrderByDescending(b => b.Name);
                    break;
                case "Name ASC":
                    genres = genres.OrderBy(b => b.Name);
                    break;
                case "Description DESC":
                    genres = genres.OrderByDescending(b => b.Description);
                    break;
                case "Description ASC":
                    genres = genres.OrderBy(b => b.Description);
                    break;
                case "Created DESC":
                    genres = genres.OrderByDescending(b => b.Created);
                    break;
                case "Created ASC":
                    genres = genres.OrderBy(b => b.Created);
                    break;
                default:
                    genres = genres.OrderBy(b => b.Id);
                    break;
            }
            int pageSize = 5;
            //return View(await authors.ToList());
            return View(await PaginatedList<Genre>.CreateAsync(genres.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Genres/Details/5
        
        public async Task<IActionResult> Details(int? id, string sortOrder, int? pageNumber)
        {
            GenreDetailsViewModel vm = new GenreDetailsViewModel();
            vm.Genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.Id == id);

            ViewBag.TitleAscDescSortParam = sortOrder == "Title ASC" ? "Title DESC" : "Title ASC";
            ViewBag.DescriptionAscDescSortParam = sortOrder == "Description ASC" ? "Description DESC" : "Description ASC";
            ViewBag.GenreAscDescSortParam = sortOrder == "Genre ASC" ? "Genre DESC" : "Genre ASC";
            ViewBag.RatingAscDescSortParam = sortOrder == "Rating ASC" ? "Rating DESC" : "Rating ASC";
            ViewBag.AuthorAscDescSortParam = sortOrder == "Authors ASC" ? "Authors DESC" : "Authors ASC";

            var books = _context.Book.Include(g => g.Genres)
                                     .Include(a => a.Authors)
                                     .Where(b => b.IsDeleted != true)
                                     .Where(b => b.Genres.Any(g => g.Id == id))
                                     .Select(b => b);
                    
           

            switch (sortOrder)
            {
                case "Title DESC":
                    books = books.OrderByDescending(b => b.Title);
                    break;
                case "Title ASC":
                    books = books.OrderBy(b => b.Title);
                    break;
                case "Description DESC":
                    books = books.OrderByDescending(b => b.Description);
                    break;
                case "Description ASC":
                    books = books.OrderBy(b => b.Description);
                    break;
                case "Genre DESC":
                    books = books.OrderByDescending(b => b.Genres);
                    break;
                case "Genre ASC":
                    books = books.OrderBy(b => b.Genres);
                    break;
                case "Rating DESC":
                    books = books.OrderByDescending(b => b.Rating);
                    break;
                case "Rating ASC":
                    books = books.OrderBy(b => b.Rating);
                    break;
                case "Authors DESC":
                    books = books.Include(a => a.Authors
                                                .OrderByDescending(b => b.FirstName));
                    break;
                case "Authors ASC":
                    books = books.Include(a => a.Authors
                                                .OrderBy(b => b.FirstName));
                    break;
                default:
                    books = books.OrderBy(b => b.Id);
                    break;
            }

            int pageSize = 2;
            vm.Books = await PaginatedList<Book>.CreateAsync(books.AsNoTracking(), pageNumber ?? 1, pageSize);
            return View(vm);
        }

        // GET: Genres/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGenreViewModel genreInput)
        {

            if (ModelState.IsValid)
            {
                Genre genreToCreate = new Genre();

                var user = await userManager.GetUserAsync(User);

                genreToCreate.Name = genreInput.Name;
                genreToCreate.Description = genreInput.Description;
                genreToCreate.Created = DateTime.Now;
                genreToCreate.CreatedBy = user.Id;

                _context.Add(genreToCreate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genreInput);
        }

        // GET: Genres/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            EditGenreViewModel vm = new EditGenreViewModel();

            
            var genre = await _context.Genre.FindAsync(id);

            vm.Id = genre.Id;
            vm.Name = genre.Name;
            vm.Description = genre.Description;
            vm.IsDeleted = genre.IsDeleted;

            if (genre == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditGenreViewModel genreInput)
        {
            if (id != genreInput.Id)
            {
                return NotFound();
            }

            Genre genreToUpdate = await _context.Genre.FindAsync(id);
            var user = await userManager.GetUserAsync(User);

            genreToUpdate.Name = genreInput.Name;
            genreToUpdate.Description = genreInput.Description;
            genreToUpdate.UpdatedBy = user.Id;
            genreToUpdate.LastUpdated = DateTime.Now;
            genreToUpdate.IsDeleted = genreInput.IsDeleted;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genreToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genreToUpdate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genreInput);
        }

        // GET: Genres/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

CoolBooks/Views/Genres/Create.cshtml
@model CreateGenreViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Lägg till en genre:</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea rows="6" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoolBooks/Views/Genres/Delete.cshtml
@model CoolBooks.Models.Genre

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoolBooks/Views/Genres/Details.cshtml
@model GenreDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Genre.Name)</h1>

<div>
    <hr />
    <dl class="row">
             <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Description)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Genre.Id">Edit |</a>
    }
    <a asp-action="Index">Back to List</a>
</div>
<partial name="_BooksTable" model="@Model.Books" />

CoolBooks/Views/Genres/Edit.cshtml
@model EditGenreViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <p>IsDeleted:</p>
            <div class="form-group form-check">
                
                <label class="form-check-label">                    
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea rows="6" asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoolBooks/Views/Genres/Index.cshtml
@*@model IEnumerable<CoolBooks.Models.Genre>*@
@model PaginatedList<CoolBooks.Models.Genre>
@{
    ViewData["Title"] = "Index";
    var controller = this.ViewContext.RouteData.Values["controller"].ToString();
    var action = this.ViewContext.RouteData.Values["action"].ToString();
    var route = ViewContext.RouteData.Values["id"];
}

<h1>Genre.</h1>


<p>Sortera på:
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.FirstNameAscDescSortParam">Namn</a>
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.DescriptionAscDescSortParam">Description</a>
    @*<a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.CreatedAscDescSortParam">Created ASC/DESC</a>*@
</p>

@foreach (var item in Model) {


         <div class="d-flex">
            <div class="m-3 d-flex flex-column justify-content-center align-content-center">
                <a class="link-secondary" asp-action="Details" asp-controller="Genres" asp-route-id="@item.Id">@item.Name</a>
                @*<a asp-controller="Books" asp-action="Details" asp-route-id="@item.Id"><img src=" @item.Book.ImagePath" class="card-img-thumbnail" alt="..." width="200px" height="297px"></a>   *@

                  <div>
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="link-secondary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a class="link-secondary" asp-action="Delete" asp-route-id="@item.Id">Delete</a>                    
                        }
                  </div>
            </div>
            <div class="d-flex flex-column m-3 border border-3 border-white p-3 rounded  w-100">
                <div>
                    <h2>
                        <a class="link-secondary" asp-action="Details" asp-controller="Genres" asp-route-id="@item.Id">@item.Name</a>
                    </h2>                   
                </div>

                <div class="d-flex">
                    <p class="text-start">@Html.DisplayFor(modelItem => item.Description)</p>
                </div>
            </div>        
        </div>
}
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
@for(int i = 1; i <= Model.TotalPages; i++)
{
    bool hej = true;
    if (Model.PageIndex == i)
    {
        hej = false;
        
    } 
    else
    {
        hej = true;
        
    }
    var currentDisabled = !hej ? "disabled" : "";
    <a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(i)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @currentDisabled">
    @i
</a>
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>