CoolBooks/Controllers/ReviewsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoolBooks.Data;
using CoolBooks.Models;
using CoolBooks.ViewModels;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using System.Security.Claims;

namespace CoolBooks.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly CoolBooksContext _context;
        private readonly UserManager<CoolBooksUser> userManager;
        private readonly SignInManager<CoolBooksUser> signInManager;
        private readonly test likedislike;
        private readonly test2 commentlikedislike;


        public ReviewsController(CoolBooksContext context, UserManager<CoolBooksUser> userManager, SignInManager<CoolBooksUser> signInManager, test likedislike, test2 commentlikedislike)
        {
            _context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.likedislike = likedislike;
            this.commentlikedislike = commentlikedislike;
        }

        // GET: Reviews
        public async Task<IActionResult> Index(string searchString, string sortOrder, string currentFilter, int? pageNumber)
        {
            ViewBag.CurrentSort = sortOrder;

            ViewBag.searchString = searchString;

            ViewBag.BookAscDescSortParam = sortOrder == "Book ASC" ? "Book DESC" : "Book ASC";
            ViewBag.TitleAscDescSortParam = sortOrder == "Title ASC" ? "Title DESC" : "Title ASC";
            ViewBag.TextAscDescSortParam = sortOrder == "Text ASC" ? "Text DESC" : "Text ASC";
            ViewBag.RatingAscDescSortParam = sortOrder == "Rating ASC" ? "Rating DESC" : "Rating ASC";
            ViewBag.CreatedAscDescSortParam = sortOrder == "Created ASC" ? "Created DESC" : "Created ASC";
            ViewBag.LikesAscDescSortParam = sortOrder == "Likes ASC" ? "Likes DESC" : "Likes ASC";
            ViewBag.DislikesAscDescSortParam = sortOrder == "Dislikes ASC" ? "Dislikes DESC" : "Dislikes ASC";
            //ViewBag.CreatedbyAscDescSortParam = sortOrder == "CreatedBy ASC" ? "CreatedBy DESC" : "CreatedBy ASC"; 
            // TODO CREATEDBY SORTERING??

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {

                searchString = currentFilter;
            }

            var coolBooksContext = _context.Review.Include(r => r.Book)
                                                  .Where(r => r.IsDeleted != true 
                                                  && r.Book.IsDeleted != true )
                                                  .Select(r => r);

            switch (sortOrder)
            {
                case "Book DESC":
                    coolBooksContext = coolBooksContext.OrderByDescending(b => b.Book.Title);
                    break;
                case "Book ASC":
                    coolBooksContext = coolBooksContext.OrderBy(b => b.Book.Title);
                    break;
                case "Title DESC":
                    coolBooksContext = coolBooksContext.OrderByDescending(b => b.Title);
                    break;
                case "Title ASC":
                    coolBooksContext = coolBooksContext.OrderBy(b => b.Title);
                    break;
                case "Text DESC":
                    coolBooksContext = coolBooksContext.OrderByDescending(b => b.Text);
                    break;
                case "Text ASC":
                    coolBooksContext = coolBooksContext.OrderBy(b => b.Text);
                    break;
                case "Rating DESC":
                    coolBooksContext = coolBooksContext.OrderByDescending(b => b.Rating);
                    break;
                case "Rating ASC":
                    coolBooksContext = coolBooksContext.OrderBy(b => b.Rating);
                    break;
                case "Likes DESC":
                    coolBooksContext = coolBooksContext.OrderByDescending(b => b.LikeCount);
                    break;
                case "Likes ASC":
                    coolBooksContext = coolBooksContext.OrderBy(b => b.LikeCount);
                    break;
                case "Dislikes DESC":
                    coolBooksContext = coolBooksContext.OrderByDescending(b => b.DisLikeCount);
                    break;
                case "Dislikes ASC":
                    coolBooksContext = coolBooksContext.OrderBy(b => b.DisLikeCount);
                    break;
                case "Created DESC":
                    coolBooksContext = coolBooksContext.OrderByDescending(b => b.Created);
                    break;
                case "Created ASC":
                    coolBooksContext = coolBooksContext.OrderBy(b => b.Created);
                    break;            
                default:
                    coolBooksContext = coolBooksContext.OrderBy(b => b.Id);
                    break;
            }
            int pageSize = 5;
            //return View(await authors.ToList());
            return View(await PaginatedList<Review>.CreateAsync(coolBooksContext.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            

            var userId = userManager.GetUserId(User);

            var review = await _context.Review
                .Include(r => r.Book)
                .Include(r => r.reportedReviews.Where(r => r.UserId == userId ))
                .Include(r => r.Comments)
                    .ThenInclude(c => c.CoolBooksUser)
                .Include(r => r.Comments)
                    .ThenInclude(c => c.CommentLikes)
                .Include(r => r.Comments)
                    .ThenInclude(c => c.comments) 
                .Include(r => r.Comments)
                    .ThenInclude(c => c.ReportedComments.Where(rc => rc.UserId == userId))
                .FirstOrDefaultAsync(m => m.Id == id);

            //gettolösning för att loada alla kommentarer...
            //update! tack vare reviewIDNested så är den här queryn betydligt mycket mindre
            var temp = await _context.Comment
                .Include(c => c.comments.Where(c => c.reviewIdNested == id))
                .Include(c => c.CommentLikes)
                .Include(c => c.ReportedComments)
                .Include(c => c.CoolBooksUser)
                .Where(c => c.reviewIdNested == id)
                .ToListAsync();

            if (review == null)
            {
                return NotFound();
            }
            
            
            ViewBag.Like = likedislike.Getlikecounts((int)id);
            ViewBag.Dislike = likedislike.Getdislikecounts((int)id);
            ViewBag.AllUserlikedislike = likedislike.GetallUser((int)id);

            //ViewBag.commentLike = commentlikedislike.Getlikecounts((int)id); // Vi får ju review id när vi försöker få kommentarens id.
            //ViewBag.commentDislike = commentlikedislike.Getdislikecounts((int)id);
            //ViewBag.commentAllUserlikedislike = commentlikedislike.GetallUser((int)id);


            return View(review);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            ViewData["BookId"] = new SelectList(_context.Book, "Id", "Description");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Text,Rating")] CreateReviewViewModel review, string? returnUrl,int id)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }


            if (ModelState.IsValid)
            {

                Review reviewToSave = new Review
                {
                    BookId = id,
                    Title = review.Title,
                    Text = review.Text,
                    Rating = review.Rating,
                    CreatedBy = userManager.GetUserId(User)
                };

                _context.Add(reviewToSave);
                await _context.SaveChangesAsync();

                //update rating on book
                var book = _context.Book.Include(b => b.Authors).Where(b => b.Id == reviewToSave.BookId).FirstOrDefault();
                
                if (book != null)
                {
                    var rating = _context.Review.Where(r => r.BookId == reviewToSave.BookId).Average(r => r.Rating);

                    book.Rating = rating;
                }

                //update rating on author
                foreach (var author in book.Authors)
                {
                    //var books = _context.Book.Include(a => a.Authors.Where(a => a.Id == author.Id)).ToList();
                    var books = _context.Author.Include(a => a.Books).FirstOrDefault(a => a.Id == author.Id);

                    List<double> avg = new List<double>();

                    foreach (var b in books.Books)
                    {
                        try
                        {
                            var rating = _context.Review.Where(r => r.BookId == b.Id).Average(r => r.Rating);
                            avg.Add(rating);
                        }
                        catch (Exception)
                        {
                            //logga felet?                            

CoolBooks/Views/Reviews/Block.cshtml
@model CoolBooks.Models.Review

@{
    ViewData["Title"] = "Delete";
}

<h1>BLOCK</h1>

<h3>Är du säker på att du vill blockera rescensionen?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Block">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Blockera" class="btn btn-danger" /> |
        <a asp-action="Index">Tillbaka</a>
    </form>
</div>

CoolBooks/Views/Reviews/Create.cshtml
@model CoolBooks.Models.Review

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoolBooks/Views/Reviews/Delete.cshtml
@model CoolBooks.Models.Review

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoolBooks/Views/Reviews/Details.cshtml
@model CoolBooks.Models.Review

@{
    ViewData["Title"] = "Details";
    var routeUrl = Url.RouteUrl(ViewContext.RouteData.Values);
}


<h1>@Html.DisplayFor(model => model.Book.Title)</h1>

<div>
    <h4>@Html.DisplayFor(model => model.Title)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Book)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Book.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)<br />
            @*<a asp-controller="Comments" asp-action="CreateReviewComment" asp-route-id="@Model.Id" asp-route-returnUrl="@routeUrl">Kommentera</a>*@
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @{double rating = (double)Model.Rating;}
            <partial name="_RatingStars" model="@rating"/> 
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
</div>
<div>
    @if (Model.CreatedBy == userManager.GetUserId(User) || User.IsInRole("Admin" ))
    {
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit |</a>
    }
    <a asp-action="Index">Back to List</a>
</div>

<partial name="_ReviewButtons" model="@Model" />
<div class="m-1"></div>
<partial name="_CommentReviewForm" model="@new CreateCommentViewModel{ ReviewId = Model.Id }" />

<h2>Kommentarer:</h2>
<partial name="_Comment" model="@Model.Comments" />

<partial name="_ButtonsScripts" />

CoolBooks/Views/Reviews/Edit.cshtml
@model EditReviewViewModel

@{
    ViewData["Title"] = "Edit";    
    var returnUrl = ViewContext.HttpContext.Request.Query["returnUrl"];
}

<h1>Edit</h1>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-returnUrl="@returnUrl" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId"></select>
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input disabled asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoolBooks/Views/Reviews/Index.cshtml
@*@model IEnumerable<CoolBooks.Models.Review>*@
@model PaginatedList<CoolBooks.Models.Review>
@{
    ViewData["Title"] = "Index";
    
    var controller = this.ViewContext.RouteData.Values["controller"].ToString();
    var action = this.ViewContext.RouteData.Values["action"].ToString();
    var route = ViewContext.RouteData.Values["id"];
  
}


<h1>Recensioner.</h1>

<p>
    Sortera på:
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.BookAscDescSortParam">Bok</a>
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.TitleAscDescSortParam">Titel</a>
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.TextAscDescSortParam">Text</a>
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.RatingAscDescSortParam">Betyg</a>
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.LikesAscDescSortParam">Likes</a>
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.DislikesAscDescSortParam">Dislikes</a>
    <a class="link-secondary" asp-controller="@controller" asp-action="@action" asp-route-id="@route" asp-route-sortOrder="@ViewBag.BookAscDescSortParam">Skapad</a>
</p>


@foreach (var item in Model) {

    <div class="d-flex">
            <div class="m-3 d-flex flex-column justify-content-center align-content-center">
                
                <a asp-controller="Books" asp-action="Details" asp-route-id="@item.Id"><img src=" @item.Book.ImagePath" class="card-img-thumbnail" alt="..." width="200px" height="297px"></a>   
                  <div>
                    @if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                    {
                       <a asp-action="Block" asp-controller="Reviews" asp-route-id="@item.Id">Block</a>
                    }
                    @if (item.CreatedBy == userManager.GetUserId(User) || User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>                        
                    }
                  </div>
            </div>
            <div class="d-flex flex-column m-3 border border-3 border-white p-3 rounded  w-100">
                <div>
                    <h2>
                        <a class="link-secondary" asp-controller="Reviews" asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a>
                    </h2>
                    
                        <a class="link-secondary" asp-controller="Books" asp-action="Details" asp-route-id="@item.BookId">@item.Book.Title</a>   
                </div>

                <div>
                    @{ double rating = (double)item.Rating;}
                    <partial name="_RatingStars" model="@rating" />
                </div>
                    
                    <p class="me-2 mb-0">Skapad: @Html.DisplayFor(modelItem => item.Created)</p>
                    <p class="me-2 mb-1">Likes: @Html.DisplayFor(modelItem => item.LikeCount) Dislikes: @Html.DisplayFor(modelItem => item.DisLikeCount)</p>

                <div class="d-flex">
                    <p class="text-start">@Html.DisplayFor(modelItem => item.Text)</p>
                
                </div>
            </div>        
        </div>

}
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
@for(int i = 1; i <= Model.TotalPages; i++)
{
    bool hej = true;
    if (Model.PageIndex == i)
    {
        hej = false;
        
    } 
    else
    {
        hej = true;
        
    }
    var currentDisabled = !hej ? "disabled" : "";
    <a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(i)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @currentDisabled">
    @i
</a>
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>